stages:
  data_ingestion:
    cmd: python src/pipeline/data_ingestion_pipeline.py
    deps:
      - src/pipeline/data_ingestion_pipeline.py
    outs:
      - artifacts/data_ingestion/downloaded_data
      - artifacts/data_ingestion/extracted_data