stages:
  data_ingestion:
    cmd: python src/pipeline/data_ingestion_pipeline.py
    deps:
      - src/pipeline/data_ingestion_pipeline.py
    outs:
      - artifacts/data_ingestion/downloaded_data
      - artifacts/data_ingestion/extracted_data

  prepare_base_model:
    cmd: python src/pipeline/prepare_base_model_pipeline.py
    deps:
      - src/pipeline/prepare_base_model_pipeline.py
    outs:
      - artifacts/prepared_basemodel/base_model

  training_model:
    cmd: python src/pipeline/model_training_pipeline.py
    deps:
      - src/pipeline/model_training_pipeline.py
    outs:
      - artifacts/model_trainer/trained_model